version: '3'

services:

  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres-network
    volumes:
      - ./script_db/initTest.sql:/docker-entrypoint-initdb.d/initTest.sql

networks:
  postgres-network:
    driver: bridge